export const IKONY = {
  'Półkolonie – sport': '🏅', 'Półkolonie – pływanie': '🏊', 'Półkolonie – piłka nożna': '⚽', 'Półkolonie – tenis': '🎾', 'Półkolonie – gimnastyka i akrobatyka': '🤸', 'Półkolonie – rolki i żeglarstwo': '⛵', 'Półkolonie – robotyka i technika': '🤖', 'Półkolonie – nauka i kreatywność': '🔬', 'Półkolonie – zabawy i animacje': '🎈', 'Półkolonie – domy kultury i harcerze': '🏕️',
  'Muzyka': '🎵', 'Języki': '🗣️', 'Plastyka i rękodzieło': '🎨', 'Programowanie i robotyka': '🤖', 'Nauka i eksperymenty': '🔬', 'Teatr i musical': '🎭', 'Inne zajęcia edukacyjne': '✨',
  'Klocki LEGO': '🧱',
  'Biblioteka': '📚', 'Salony gier i VR': '🕹️',
  'Pływanie': '🏊', 'Taniec': '💃', 'Sztuki walki': '🥋', 'Piłka nożna': '⚽', 'Tenis i badminton': '🎾',
  'Gimnastyka i akrobatyka': '🤸', 'Zajęcia ogólnorozwojowe': '🏃', 'Narty i snowboard': '⛷️', 'Łyżwy i rolki': '⛸️',
  'Żeglarstwo i kajaki': '⛵', 'Wspinaczka': '🧗', 'Jazda konna': '🐎', 'Kluby i inne sporty': '🏅',
  'Sala zabaw': '🤸', 'Plac zabaw': '🛝', 'Park': '🌳', 'Muzeum': '🏛️', 'Teatr': '🎭', 'Kino': '🎬',
  'Basen': '🏊', 'Szkoły pływania': '🐠', 'Sport / zajęcia ruchowe': '⚽', 'Zajęcia sportowe': '⚽', 'Boiska i sport na polu': '🏀', 'Koncerty dla dzieci': '🎻', 'Zajęcia mama-dziecko': '👶',
  'Zajęcia edukacyjne i artystyczne': '🎨', 'Instytucja kultury': '🎪', 'Filharmonia / koncerty': '🎻',
  'Kawiarnie i restauracje dla rodzin': '🧁', 'Escape room': '🗝️', 'Laser tag': '🔦',
  'Gospodarstwo edukacyjne': '🐐', 'Zbiornik wodny': '🏖️', 'Wesołe miasteczko': '🎡', 'Park linowy': '🧗',
  'Skatepark i street workout': '🛹', 'Tor saneczkowy': '🛷', 'Ścieżka edukacyjna': '🥾',
  'Zdrowie i relaks': '🧂', 'Półkolonie': '🏕️',
};

// Krótsze nazwy na kafelkach filtrów (na kartach zostają pełne).
export const SKROTY = {
  'Półkolonie – sport': 'Sport', 'Półkolonie – pływanie': 'Pływanie', 'Półkolonie – piłka nożna': 'Piłka nożna', 'Półkolonie – tenis': 'Tenis', 'Półkolonie – gimnastyka i akrobatyka': 'Gimnastyka', 'Półkolonie – rolki i żeglarstwo': 'Rolki i żagle', 'Półkolonie – robotyka i technika': 'Robotyka', 'Półkolonie – nauka i kreatywność': 'Nauka i kreatywność', 'Półkolonie – zabawy i animacje': 'Zabawy', 'Półkolonie – domy kultury i harcerze': 'Domy kultury i harcerze',
  'Inne zajęcia edukacyjne': 'Inne',
  'Programowanie i robotyka': 'Programowanie',
  'Plastyka i rękodzieło': 'Plastyka',
  'Nauka i eksperymenty': 'Nauka',
  'Kawiarnie i restauracje dla rodzin': 'Kawiarnie',
  'Zajęcia edukacyjne i artystyczne': 'Edukacja i sztuka',
  'Gospodarstwo edukacyjne': 'Zagrody',
  'Boiska i sport na polu': 'Boiska',
  'Koncerty dla dzieci': 'Koncerty',
  'Zajęcia mama-dziecko': 'Mama i dziecko',
  'Instytucja kultury': 'Domy kultury',
  'Ścieżka edukacyjna': 'Ścieżki',
  'Zdrowie i relaks': 'Groty solne',
  'Zbiornik wodny': 'Kąpieliska',
  'Gimnastyka i akrobatyka': 'Gimnastyka',
  'Zajęcia ogólnorozwojowe': 'Ogólnorozwojowe',
  'Kluby i inne sporty': 'Inne sporty',
  'Żeglarstwo i kajaki': 'Żeglarstwo',
  'Wesołe miasteczko': 'Parki rozrywki',
  'Kawiarnie i restauracje dla rodzin': 'Kawiarnie',
};
